import fs from "node:fs";
import path from "node:path";

function getVariableName(pkgName: string): string {
  const clean = pkgName
    .replace(/^@/, "")
    .replace(/\//, "-")
    .replace(/-plugin$/, "")
    .replace(/-module$/, "");

  // Special cases to match original naming if needed
  if (clean === "blog") return "BlogModulePlugin";
  if (clean === "panel") return "PanelModulePlugin";
  if (clean === "devtools") return "DevtoolsModulePlugin";
  if (clean === "backup") return "BackupModulePlugin";

  return (
    clean
      .split("-")
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join("") + "Plugin"
  );
}

export function regeneratePluginsRegistry(rootDir: string) {
  const pluginsFound: {
    name: string;
    varName: string;
  }[] = [];

  // 1. Scan package.json dependencies
  const pkgPath = path.join(rootDir, "package.json");
  if (fs.existsSync(pkgPath)) {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
    const deps = {
      ...(pkg.dependencies || {}),
      ...(pkg.devDependencies || {}),
    };

    for (const depName of Object.keys(deps)) {
      let isPlugin = depName.endsWith("-plugin") && depName !== "@veap/cli";

      if (!isPlugin) {
        // Check node_modules package.json
        const depPkgPath = path.join(
          rootDir,
          "node_modules",
          depName,
          "package.json",
        );
        if (fs.existsSync(depPkgPath)) {
          try {
            const depPkg = JSON.parse(fs.readFileSync(depPkgPath, "utf-8"));
            if ((depPkg.veap || depPkg.veap)?.type === "plugin") {
              isPlugin = true;
            }
          } catch (_) {}
        }

        // Check plugins/ and modules/ local folders
        const cleanName = depName
          .replace(/^@veap\//, "")
          .replace(/^@veap\//, "")
          .replace(/^@contractor\//, "");
        const localPluginPkgPath = path.join(
          rootDir,
          "plugins",
          cleanName,
          "package.json",
        );
        const localModulePkgPath = path.join(
          rootDir,
          "modules",
          cleanName,
          "package.json",
        );

        for (const candidatePath of [localPluginPkgPath, localModulePkgPath]) {
          if (fs.existsSync(candidatePath)) {
            try {
              const depPkg = JSON.parse(
                fs.readFileSync(candidatePath, "utf-8"),
              );
              if (
                depPkg.veap?.type === "plugin" ||
                depPkg.veap?.type === "module"
              ) {
                isPlugin = true;
                break;
              }
            } catch (_) {}
          }
        }
      }

      if (isPlugin) {
        pluginsFound.push({
          name: depName,
          varName: getVariableName(depName),
        });
      }
    }
  }

  // Generate code for plugins.gen.ts
  let code =
    "" +
    "/**\n * FILE AUTOMATICALLY GENERATED BY veap/cli\n * DO NOT EDIT THIS FILE MANUALLY!\n */\n\n";

  // Write imports
  for (const p of pluginsFound) {
    code += "import { default as " + p.varName + ' } from "' + p.name + '";\n';
  }

  code += "\nexport const plugins = [\n";
  for (const p of pluginsFound) {
    code += "  " + p.varName + ",\n";
  }
  code += "];\n";

  const pluginsGenPath = path.join(rootDir, "lib", "plugins.gen.ts");
  // Make sure lib/ directory exists
  const libDir = path.dirname(pluginsGenPath);
  if (!fs.existsSync(libDir)) {
    fs.mkdirSync(libDir, { recursive: true });
  }
  fs.writeFileSync(pluginsGenPath, code, "utf-8");
  console.log(
    "[Veap CLI] Regenerated " +
      pluginsGenPath +
      " with " +
      pluginsFound.length +
      " plugins.",
  );
}
