import fs from "node:fs/promises";
import path from "node:path";

const stub = `import type { Schema } from "@veap/core/database";

export default {
  name: "{{name}}",
  async up(_db: any, schema: Schema) {
    await schema.createTable("{{tableName}}", (table) => {
      table.increments("id");
      
      table.timestamps();
    });
  },
  async down(_db: any, schema: Schema) {
    await schema.dropTableIfExists("{{tableName}}");
  },
};
`;

async function updateIndexFile(migrationsDir: string) {
  const indexFile = path.join(migrationsDir, "index.ts");

  // Get all .ts files except index.ts
  const files = await fs.readdir(migrationsDir);
  const migrationFiles = files
    .filter((f) => f.endsWith(".ts") && f !== "index.ts")
    .sort();

  const imports: string[] = [];
  const exports: string[] = [];

  for (const file of migrationFiles) {
    const name = file.replace(".ts", "");
    const varName = `m${name.replace(/[^a-zA-Z0-9]/g, "_")}`;
    imports.push(`import { default as ${varName} } from "./${name}";`);
    exports.push(varName);
  }

  const content = `// This file is auto-generated by Veap CLI. Do not edit manually.
${imports.join("\n")}

export const appMigrations = [
  ${exports.join(",\n  ")}
];
`;

  await fs.writeFile(indexFile, content, "utf-8");
}

export async function generateMigration(name: string) {
  try {
    const timestamp = new Date()
      .toISOString()
      .replace(/[-:T]/g, "")
      .slice(0, 14);
    const fileName = `${timestamp}_${name}`;

    let tableName = name;
    if (name.startsWith("create_") && name.endsWith("_table")) {
      tableName = name.replace("create_", "").replace("_table", "");
    }

    const content = stub
      .replace(/{{name}}/g, fileName)
      .replace(/{{tableName}}/g, tableName);

    const migrationsDir = path.join(process.cwd(), "migrations");

    await fs.mkdir(migrationsDir, { recursive: true });

    const filePath = path.join(migrationsDir, `${fileName}.ts`);
    await fs.writeFile(filePath, content, "utf-8");

    await updateIndexFile(migrationsDir);

    console.log(`\n✅ Migration created: migrations/${fileName}.ts`);
    console.log(`✅ Updated migrations/index.ts`);
  } catch (error) {
    console.error("Failed to generate migration:", error);
    process.exit(1);
  }
}
