# Stage 1: Base image (yarn berry)
FROM node:22-alpine AS base
RUN apk add --no-cache libc6-compat

RUN corepack enable
RUN corepack prepare yarn@4.9.2 --activate

# Stage 2: Install dependencies
FROM base AS deps
WORKDIR /app
COPY . .
RUN --mount=type=cache,id=yarn,target=/root/.yarn/berry/cache \
    yarn config set enableNetworkConcurrency 8 && \
    yarn install --immutable

# Stage 3: Build the project
FROM base AS builder
WORKDIR /app
COPY --from=deps /app ./
RUN yarn build

# Stage 4: Production runner
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Automatically leverage output traces to reduce image size
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "./server.js"]
